---
- hosts:
    - database
    - database_replica
  user: "{{ ansible_ssh_user }}"
  become: true
  become_user: root
  become_method: sudo
  gather_facts: True
  tasks:
  - ansible.builtin.debug:
      var: hostvars['database'].ansible_default_ipv4.address
  vars_files:
    - ./vars/*.yml

  roles:
    - /etc/ansible/roles/postgresql
