---
- hosts:
    - database
    - database_replica
  user: "{{ ansible_ssh_user }}"
  become: true
  become_user: root
  become_method: sudo
  gather_facts: True

  tasks:
    - name: Stop and disable PostgreSQL on RedHat
      ansible.builtin.service:
        name: postgresql
        state: stopped
        enabled: no
      when: ansible_os_family == 'RedHat'

    - name: Stop and disable PostgreSQL on Debian
      ansible.builtin.service:
        name: postgresql
        state: stopped
        enabled: no
      when: ansible_os_family == 'Debian'

    - name: Remove PostgreSQL on RedHat
      ansible.builtin.command: /usr/bin/yum remove -y postgresql*
      when: ansible_os_family == 'RedHat'

    - name: Remove PostgreSQL on Debian
      ansible.builtin.command: /usr/bin/apt-get remove -y postgresql*
      when: ansible_os_family == 'Debian'
