- hosts: "{{ project }}"
  become: yes
  tasks:
    - name: Include HAProxy clear tasks
      include_role:
        name: haproxy
        tasks_from: clear.yml
      when:
        - role == 'haproxy'
        - action == 'clear'

    - name: Include Keepalived clear tasks
      include_role:
        name: keepalived
        tasks_from: clear.yml
      when:
        - role == 'keepalived'
        - action == 'clear'

    - name: Include HAProxy install tasks
      include_role:
        name: haproxy
      when:
        - role == 'haproxy'
        - action == 'install'

    - name: Include Keepalived install tasks
      include_role:
        name: keepalived
      when:
        - role == 'keepalived'
        - action == 'install'

