- hosts: "{{ project }}"
  become: yes
  tasks:
    - name: Include HAProxy role
      include_role:
        name: haproxy
        tasks_from: clear.yml
      when: role == 'Haproxy'

    - name: Include Keepalived role
      include_role:
        name: keepalived
        tasks_from: clear.yml
      when: role == 'Keepalived'

