- name: Remove Keepalived on Debian-based systems
  apt:
    name: "{{ keepalived_pkg }}"
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove Keepalived on Red Hat-based systems
  yum:
    name: "{{ keepalived_pkg }}"
    state: removed
    use_backend: "{{ 'yum' if ansible_facts['yum_version'] is version('3', '<') else 'dnf' }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Remove Keepalived configuration files
  file:
    path: /etc/keepalived
    state: absent
  become: true
