- name: Apply Keepalived configuration for MASTER
  template:
    src: "keepalived_master.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  when: hostvars[inventory_hostname]['role'] == 'master'
  notify:
    - Restart Keepalived
  become: true

- name: Apply Keepalived configuration for SLAVE
  template:
    src: "keepalived_slave.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  when: hostvars[inventory_hostname]['role'] == 'slave'
  notify:
    - Restart Keepalived
  become: true

- name: Restart Keepalived
  service:
    name: keepalived
    state: restarted
  become: true

- name: Display Keepalived status
  ansible.builtin.shell: |
    systemctl status keepalived | cat
  register: keepalived_status
  become: true

- name: Show Keepalived status output
  debug:
    msg: |
      {{ keepalived_status.stdout }}

# - name: Display Keepalived status
#   command: systemctl status keepalived
#   register: keepalived_status
#   become: true

# - name: Extract Active status line
#   set_fact:
#     keepalived_active_status_line: "{{ keepalived_status.stdout | regex_search('Active: .*', multiline=True) }}"

# - name: Determine status color
#   set_fact:
#     keepalived_status_color: "{% if keepalived_active_status_line is search('active \\(running\\)') %}\u001b[32m{% else %}\u001b[31m{% endif %}"

# - name: Highlight Active status line
#   set_fact:
#     keepalived_highlighted_active_status: "{{ keepalived_status_color }}{{ keepalived_active_status_line }}\u001b[0m"

# - name: Format Keepalived status output
#   set_fact:
#     keepalived_formatted_status: "{{ keepalived_status.stdout | regex_replace(keepalived_active_status_line, keepalived_highlighted_active_status) }}"

# - name: Show Keepalived status output
#   debug:
#     msg: |
#       {{ keepalived_formatted_status }}