- name: Install Keepalived on Debian-based systems
  apt:
    name: "{{ keepalived_pkg }}"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Install Keepalived on Red Hat-based systems
  yum:
    name: "{{ keepalived_pkg }}"
    state: present
    use_backend: "{{ 'yum' if ansible_facts['yum_version'] is version('3', '<') else 'dnf' }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Display Keepalived status
  ansible.builtin.shell: |
    systemctl status keepalived | cat
  register: keepalived_status
  become: true

- name: Show Keepalived status output
  debug:
    msg: |
      {{ keepalived_status.stdout }}