- name: Configure master server for Debian
  lineinfile:
    state: present
    backrefs: true
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ pgsqlrep_postgres_conf_lines }}"
  notify: restart postgresql
  become: true
  when: ansible_os_family == 'Debian'

- name: Configure master server for Redhat,Centos
  lineinfile:
    state: present
    backrefs: true
    # dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/postgresql.conf"
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ pgsqlrep_postgres_conf_lines }}"
  notify: restart postgresql
  become: true
  when: ansible_os_family == 'RedHat'

- name: Create replication user account
  postgresql_user:
    name: "{{ pgsqlrep_user }}"
    password: "{{ pgsqlrep_password }}"
    role_attr_flags: replication
  become: true
  become_user: postgres

- name: Create replication user account if Debian
  postgresql_user:
    name: "{{ pgsqlrep_user }}"
    password: "{{ pgsqlrep_password }}"
    role: replication
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'

# - name: Add trust in pg_hba.conf
#   lineinfile:
#     state: present
#     # dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/pg_hba.conf"
#     dest: "{{ postgresql_data_dir }}/pg_hba.conf"
#     regexp: 'host.*replication.*{{ pgsqlrep_replica_address }}/32.*trust'
#     line: 'host    replication    {{ pgsqlrep_user }}  {{ pgsqlrep_replica_address }}/32 trust'
#   # loop: "{{ pgsqlrep_replica_address }}"
#   notify: restart postgresql
#   become: true