---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: initialize.yml
- include_tasks: configure.yml

- include_tasks: configure_slave.yml
  vars:
    master_host_ip: "{{ hostvars['database'].ansible_default_ipv4.address }}"
    # slave_host_ip: "{{ hostvars['database_replica'].ansible_host }}"
  when: ansible_host == master_host_ip

- include_tasks: configure_slave.yml
  vars:
    slave_host_ip: "{{ hostvars['database_replica'].ansible_default_ipv4.address }}"
    # slave_host_ip: "{{ hostvars['database_replica'].ansible_host }}"
  when: ansible_host == slave_host_ip

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
  become: true

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml
