- hosts: "{{ project }}"
  become: yes
  vars:
    role: "{{ role }}"
    action: "{{ action }}"
  tasks:
    - name: Include HAProxy clear tasks
      include_tasks: clear.yml
      # include_role:
      #   name: haproxy
      #   tasks_from: clear.yml
      when:
        - role == 'Haproxy'
        - action == 'clear'

    # - name: Include Keepalived clear tasks
    #   include_role:
    #     name: keepalived
    #     tasks_from: clear.yml
    #   when:
    #     - role == 'Keepalived'
    #     - action == 'clear'


