- hosts: "{{ project }}"
  become: yes
  vars:
    role: "{{ role }}"
    action: "{{ action }}"
  tasks:
    - name: Include HAProxy configuration tasks
      include_role:
        name: haproxy
        tasks_from: configure.yml
      when: role == 'Haproxy' and action == 'update'
