- name: Copy FixOS.sh script to target server root directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/FixOS.sh"
    dest: /FixOS.sh
    mode: '0755'
  become: true

- name: Make FixOS.sh executable
  ansible.builtin.command: chmod +x /FixOS.sh
  become: true

- name: Run FixOS.sh script as root
  ansible.builtin.shell: |
    /FixOS.sh
  become: true
  become_user: root
  register: fix_os_script_output
  ignore_errors: true

- name: Show FixOS.sh script output
  ansible.builtin.debug:
    var: fix_os_script_output.stdout_lines
