---
- name: Run Setup_Server.sh script
  ansible.builtin.shell: |
    chmod +x {{ ansible_env.HOME }}/{{ project }}/scripts/Setup_Server.sh
    {{ ansible_env.HOME }}/{{ project }}/scripts/Setup_Server.sh
  become: true
  environment:
    HOSTNAME: "{{ hostname }}"
    USERNAME: "{{ username }}"
    PASSWORD: "{{ password }}"
    REBOOT: "{{ reboot }}"
    INSTALL_DOCKER: "{{ installDocker }}"
    ADD_SSH_KEY: "{{ addSSHKey }}"
    ADD_ALIASES: "{{ addAliases }}"
    CREATE_USER: "{{ createUser }}"