- name: Remove HAProxy on Debian-based systems
  apt:
    name: "{{ haproxy_pkg }}"
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove HAProxy on Red Hat-based systems
  yum:
    name: "{{ haproxy_pkg }}"
    state: removed
    use_backend: "{{ 'yum' if ansible_facts['yum_version'] is version('3', '<') else 'dnf' }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Remove HAProxy configuration files
  file:
    path: /etc/haproxy
    state: absent
  become: true
