- name: Unmask HAProxy service
  command: systemctl unmask haproxy
  become: true
  ignore_errors: true

- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped
  become: true

- name: Disable HAProxy service
  service:
    name: haproxy
    enabled: no
  become: true

- name: Remove HAProxy package on Debian-based systems
  apt:
    name: haproxy
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove HAProxy package on Red Hat-based systems
  yum:
    name: haproxy
    state: removed
    use_backend: "{{ 'yum' if ansible_facts['yum_version'] is version('3', '<') else 'dnf' }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Remove HAProxy configuration directory
  file:
    path: /etc/haproxy
    state: absent
  become: true

- name: Remove HAProxy log directory
  file:
    path: /var/log/haproxy
    state: absent
  become: true

- name: Remove HAProxy run directory
  file:
    path: /run/haproxy
    state: absent
  become: true

- name: Remove HAProxy binary
  file:
    path: /usr/sbin/haproxy
    state: absent
  become: true

- name: Remove HAProxy systemd service file on Debian-based systems
  file:
    path: /lib/systemd/system/haproxy.service
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove HAProxy systemd service file on Red Hat-based systems
  file:
    path: /usr/lib/systemd/system/haproxy.service
    state: absent
  when: ansible_os_family == "RedHat"
  become: true

- name: Remove HAProxy service links
  file:
    path: /etc/systemd/system/multi-user.target.wants/haproxy.service
    state: absent
  become: true
  ignore_errors: true

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: true

- name: Ensure HAProxy is not running
  shell: |
    if pgrep haproxy; then
      pkill -f haproxy
    fi
  become: true
  ignore_errors: true
