- name: Unmask HAProxy service
  command: systemctl unmask haproxy
  become: true
  ignore_errors: true

- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped
  become: true

- name: Disable HAProxy service
  service:
    name: haproxy
    enabled: no
  become: true

# - name: Mask HAProxy service
#   command: systemctl mask haproxy
#   become: true
#   ignore_errors: true

- name: Remove HAProxy package on Debian-based systems
  apt:
    name: haproxy
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove HAProxy package on Red Hat-based systems
  yum:
    name: haproxy
    state: removed
    use_backend: "{{ 'yum' if ansible_facts['yum_version'] is version('3', '<') else 'dnf' }}"
  when: ansible_os_family == "RedHat"
  become: true

- name: Remove HAProxy configuration files
  file:
    path: /etc/haproxy
    state: absent
  become: true

- name: Remove HAProxy systemd service file on Debian-based systems
  file:
    path: /lib/systemd/system/haproxy.service
    state: absent
  when: ansible_os_family == "Debian"
  become: true

- name: Remove HAProxy systemd service file on Red Hat-based systems
  file:
    path: /usr/lib/systemd/system/haproxy.service
    state: absent
  when: ansible_os_family == "RedHat"
  become: true

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: true
