- name: Update HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - Restart HAProxy
  become: true

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
  become: true

- name: Display HAProxy status
  command: systemctl status haproxy
  register: haproxy_status
  become: true

- name: Show HAProxy status output
  debug:
    var: haproxy_status.stdout